-- ─────────────────────────────────────────────────────────────
-- ThirdLeaf — Initial Migration
-- Generated by Drizzle Kit
-- Run: npm run db:migrate (from packages/db)
-- ─────────────────────────────────────────────────────────────

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ── Enums ─────────────────────────────────────────────────────

DO $$ BEGIN
  CREATE TYPE "plan" AS ENUM('solo', 'quant_builder', 'prop_mentor');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE "role" AS ENUM('trader', 'admin');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE "broker" AS ENUM('zerodha', 'upstox', 'angel_one', 'fyers', 'dhan', 'other');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE "trade_direction" AS ENUM('long', 'short');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE "trade_status" AS ENUM('open', 'closed', 'cancelled');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE "asset_class" AS ENUM('equity', 'fno', 'currency', 'commodity', 'crypto');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- ── Users Table ────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "users" (
  "id"         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "clerk_id"   VARCHAR(256) NOT NULL UNIQUE,
  "email"      VARCHAR(320) NOT NULL UNIQUE,
  "name"       VARCHAR(256) NOT NULL,
  "plan"       "plan" NOT NULL DEFAULT 'solo',
  "role"       "role" NOT NULL DEFAULT 'trader',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── User Settings Table ────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "user_settings" (
  "id"               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id"          UUID NOT NULL UNIQUE REFERENCES "users"("id") ON DELETE CASCADE,
  "default_broker"   "broker",
  "default_currency" VARCHAR(3) NOT NULL DEFAULT 'INR',
  "risk_per_trade"   DECIMAL(5, 2) NOT NULL DEFAULT 1.00,
  "daily_loss_limit" DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  "timezone"         VARCHAR(64) NOT NULL DEFAULT 'Asia/Kolkata',
  "notifications"    JSONB NOT NULL DEFAULT '{
    "email": true,
    "pushOnTradeClose": true,
    "dailySummary": true,
    "weeklyReport": false,
    "riskAlerts": true
  }',
  "created_at"       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at"       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Trades Table ───────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "trades" (
  "id"             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id"        UUID NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "symbol"         VARCHAR(50) NOT NULL,
  "exchange"       VARCHAR(20) NOT NULL DEFAULT 'NSE',
  "asset_class"    "asset_class" NOT NULL DEFAULT 'equity',
  "direction"      "trade_direction" NOT NULL,
  "status"         "trade_status" NOT NULL DEFAULT 'open',
  "broker"         "broker" NOT NULL,
  "quantity"       DECIMAL(15, 4) NOT NULL,
  "entry_price"    DECIMAL(15, 4) NOT NULL,
  "exit_price"     DECIMAL(15, 4),
  "stop_loss"      DECIMAL(15, 4),
  "take_profit"    DECIMAL(15, 4),
  "entry_time"     TIMESTAMPTZ NOT NULL,
  "exit_time"      TIMESTAMPTZ,
  "pnl"            DECIMAL(15, 4),
  "pnl_percentage" DECIMAL(8, 4),
  "charges"        JSONB,
  "tags"           TEXT[] NOT NULL DEFAULT '{}',
  "notes"          TEXT,
  "setup_id"       UUID,
  "screenshots"    TEXT[] NOT NULL DEFAULT '{}',
  "created_at"     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at"     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Indexes ────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS "idx_users_clerk_id" ON "users"("clerk_id");
CREATE INDEX IF NOT EXISTS "idx_users_email" ON "users"("email");
CREATE INDEX IF NOT EXISTS "idx_trades_user_id" ON "trades"("user_id");
CREATE INDEX IF NOT EXISTS "idx_trades_symbol" ON "trades"("symbol");
CREATE INDEX IF NOT EXISTS "idx_trades_status" ON "trades"("status");
CREATE INDEX IF NOT EXISTS "idx_trades_entry_time" ON "trades"("entry_time");

-- ── Updated_at trigger function ────────────────────────────────

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE OR REPLACE TRIGGER update_users_updated_at
  BEFORE UPDATE ON "users"
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE OR REPLACE TRIGGER update_user_settings_updated_at
  BEFORE UPDATE ON "user_settings"
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE OR REPLACE TRIGGER update_trades_updated_at
  BEFORE UPDATE ON "trades"
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
